## **ANÁLISE BRASILEIRÃO**

Aqui teremos como objetivo encontrar padrões e diferenças entres os anos dos campeonatos e quem sabe predizer o novo campeão.

**Obs.:** Será utilizado _APENAS_ análise de tabelas e gráficos, sem uso de _ML_

1. **CARREGANDO O ARQUIVO**
2. **REALIZANDO ANÁLISE (ENTRE OS CAMPEÕES)**

### **1 - CARREGANDO O ARQUIVO**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('tabelasBrasileirao.csv')
df

,Pos.,Equipes,P,J,V,E,D,GP,GC,SG,%,Classificação ou rebaixamento,ano
0,1,Cruzeiro,100,46,31,7,8,102,47,55,72,Copa Libertadores,2003
1,2,Santos,87,46,25,12,9,93,60,33,63,Copa Libertadores,2003
2,3,São Paulo,78,46,22,12,12,81,67,14,56,Copa Libertadores,2003
3,4,São Caetano,74,46,19,14,13,53,37,16,53,Copa Libertadores,2003
4,5,Coritiba,73,46,21,10,15,67,58,9,52,Copa Libertadores,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,16,Juventude,46,38,11,13,14,36,44,-8,40,NaN,2021
386,17,Grêmio,43,38,12,7,19,44,51,-7,38,Rebaixados à Série B,2021
387,18,Bahia,43,38,11,10,17,42,51,-9,38,Rebaixados à Série B,2021
388,19,Sport,38,38,9,11,18,24,37,-13,33,Rebaixados à Série B,2021
389,20,Chapecoense,15,38,1,12,25,27,67,-40,13,Rebaixados à Série B,2021

In [95]:
df['%_GC'] = df['GC'] / df['GP']

In [96]:
fd_dict = {
            'MG':['Cruzeiro', 'Atlético Mineiro','América Mineiro','Ipatinga'],
            'SP':['Santos', 'São Paulo', 'São Caetano','Guarani', 'Palmeiras', 'Corinthians', 'Ponte Preta', 'Portuguesa','Grêmio Barueri', 'Santo André','Grêmio Prudente','Red Bull Bragantino'],
            'RS':['Internacional', 'Grêmio','Juventude'], 
            'SC':['Joinville','Figueirense','Criciúma','Avaí','Chapecoense'],
            'RJ':['Flamengo', 'Fluminense', 'Vasco da Gama', 'Botafogo'],
            'GO':['Goiás', 'Atlético Goianiense'],
            'PR':['Paraná','Athletico Paranaense', 'Coritiba'],
            'CE':['Fortaleza','Ceará'],
            'PA':['Paysandu'],
            'BA':['Bahia', 'Vitória'],
            'DF':['Brasiliense'], 
            'PE': ['Santa Cruz', 'Sport', 'Náutico'],
            'RN':['América de Natal'], 
            'MT':['Cuiabá'],
            'AL':['CSA']
        }



for fd in fd_dict:
    df.loc[df['Equipes'].isin(fd_dict[fd]),'fd'] = fd
df

,Pos.,Equipes,P,J,V,E,D,GP,GC,SG,%,Classificação ou rebaixamento,ano,fd,%_GC
0,1,Cruzeiro,100,46,31,7,8,102,47,55,72,Copa Libertadores,2003,MG,0.460784
1,2,Santos,87,46,25,12,9,93,60,33,63,Copa Libertadores,2003,SP,0.645161
2,3,São Paulo,78,46,22,12,12,81,67,14,56,Copa Libertadores,2003,SP,0.827160
3,4,São Caetano,74,46,19,14,13,53,37,16,53,Copa Libertadores,2003,SP,0.698113
4,5,Coritiba,73,46,21,10,15,67,58,9,52,Copa Libertadores,2003,PR,0.865672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,16,Juventude,46,38,11,13,14,36,44,-8,40,NaN,2021,RS,1.222222
386,17,Grêmio,43,38,12,7,19,44,51,-7,38,Rebaixados à Série B,2021,RS,1.159091
387,18,Bahia,43,38,11,10,17,42,51,-9,38,Rebaixados à Série B,2021,BA,1.214286
388,19,Sport,38,38,9,11,18,24,37,-13,33,Rebaixados à Série B,2021,PE,1.541667
389,20,Chapecoense,15,38,1,12,25,27,67,-40,13,Rebaixados à Série B,2021,SC,2.481481

## **2 - REALIZANDO ANÁLISE (ENTRE OS CAMPEÕES)**

Vamos aqui buscar compreender:
1. Quem foram os maiores campeões?
2. Quais estados federativos que possuem mais títulos?
3. Comparação das campanhas entre eles;
4. Quais as sequências de títulos?
5. Existe diferença entre as edições disputadas?

In [97]:
df_campeoes = df[df['Pos.'] == 1]

### **1. Quem foram os maiores campeões**

Abaixo temos um ranking do campeão com maior pontuação até com a menor
Obs.: Estamos usando todas as edições desde 2003. Lembrando que houve mudança na quantidade de equipes com o passar do tempo, vamos ir verificando isso com o passar da análise.

### 1.1 - Ranking geral

In [98]:
df_campeoes.sort_values(by='P', ascending=False)

,Pos.,Equipes,P,J,V,E,D,GP,GC,SG,%,Classificação ou rebaixamento,ano,fd,%_GC
0,1,Cruzeiro,100,46,31,7,8,102,47,55,72,Copa Libertadores,2003,MG,0.460784
330,1,Flamengo,90,38,28,6,4,86,37,49,79,Copa Libertadores,2019,RJ,0.430233
24,1,Santos,89,46,27,8,11,103,58,45,64,Copa Libertadores,2004,SP,0.563107
370,1,Atlético Mineiro,84,38,26,6,6,67,34,33,74,Copa Libertadores,2021,MG,0.507463
250,1,Corinthians,81,38,24,9,5,71,31,40,71,Copa Libertadores,2015,SP,0.436620
48,1,Corinthians,81,42,24,9,9,87,59,28,64,Copa Libertadores,2005,SP,0.678161
230,1,Cruzeiro,80,38,24,8,6,67,38,29,70,Copa Libertadores,2014,MG,0.567164
270,1,Palmeiras,80,38,24,8,6,62,32,30,70,Copa Libertadores,2016,SP,0.516129
310,1,Palmeiras,80,38,23,11,4,64,26,38,70,Copa Libertadores,2018,SP,0.406250
70,1,São Paulo,78,38,22,12,4,66,32,34,68,Copa Libertadores,2006,SP,0.484848
90,1,São Paulo,77,38,23,8,7,55,19,36,68,Copa Libertadores,2007,SP,0.345455
190,1,Fluminense,77,38,22,11,5,61,33,28,67,Copa Libertadores,2012,RJ,0.540984
210,1,Cruzeiro,76,38,23,7,8,77,37,40,67,Copa Libertadores,2013,MG,0.480519
110,1,São Paulo,75,38,21,12,5,66,36,30,66,Copa Libertadores,2008,SP,0.545455
290,1,Corinthians,72,38,21,9,8,50,30,20,63,Copa Libertadores,2017,SP,0.600000
150,1,Fluminense,71,38,20,11,7,62,36,26,62,Copa Libertadores,2010,RJ,0.580645
170,1,Corinthians,71,38,21,8,9,53,36,17,62,Copa Libertadores,2011,SP,0.679245
350,1,Flamengo,71,38,21,8,9,68,48,20,62,Copa Libertadores,2020,RJ,0.705882
130,1,Flamengo,67,38,19,10,9,58,44,14,59,Copa Libertadores,2009,RJ,0.758621

#### 1.1 - Observações

Notamos que, quando vemos todas as edições (mesmo com número de jogos diferentes), temos o **Cruzeiro** com a maior pontuação, seguido do **Flamengo**, sendo este título no ano de _2019_ com _38_ jogos totais, um feito muito bom sendo que o **Cruzeiro** teve _46_ jogos; quando olhamos o **terceiro** colocado, temos o **Santos**, que foi campeão com o mesmo número de jogos que o **Cruzeiro**, o **Corinthians** que foi campeão em _2005_, tendo _42_ jogos, esta em **_6º_**, tendo a mesma pontuação de sua campanha de _2015_ com a mesma pontuação.

As **%** (porcentagens) não possuem relação com as _potuações_ e _quantidade de jogos_. **Flamengo** de 2019 tem a melhor **%** de todos os clubes, inclusive que o **Santos** de _2004_ e **Corinthians** de _2005_.

Gols Marcados e sofridos (GP e GC
Então, podemos dizer que:
- Número de jogos totais não implica em boas campanhas.
- Porcentagens não tem relação com pontuação e quantidade de jogos.

### 1.2 - Ranking por número de jogos

In [99]:
columns = list(df_campeoes.columns)
columns.remove("Pos.")
columns.remove("Classificação ou rebaixamento")
columns

['Equipes',
 'P',
 'J',
 'V',
 'E',
 'D',
 'GP',
 'GC',
 'SG',
 '%',
 'ano',
 'fd',
 '%_GC']

In [100]:
for numero_jogos in df_campeoes['J'].unique():
    print(f'Quantidade de jogos no campeonato: {numero_jogos}')
    print(df_campeoes[columns].groupby(by='J').get_group(numero_jogos).sort_values(by='P', ascending=False))
    print('\n')

Quantidade de jogos no campeonato: 46
     Equipes    P   J   V  E   D   GP  GC  SG   %   ano  fd      %_GC
0   Cruzeiro  100  46  31  7   8  102  47  55  72  2003  MG  0.460784
24    Santos   89  46  27  8  11  103  58  45  64  2004  SP  0.563107


Quantidade de jogos no campeonato: 42
        Equipes   P   J   V  E  D  GP  GC  SG   %   ano  fd      %_GC
48  Corinthians  81  42  24  9  9  87  59  28  64  2005  SP  0.678161


Quantidade de jogos no campeonato: 38
              Equipes   P   J   V   E  D  GP  GC  SG   %   ano  fd      %_GC
330          Flamengo  90  38  28   6  4  86  37  49  79  2019  RJ  0.430233
370  Atlético Mineiro  84  38  26   6  6  67  34  33  74  2021  MG  0.507463
250       Corinthians  81  38  24   9  5  71  31  40  71  2015  SP  0.436620
230          Cruzeiro  80  38  24   8  6  67  38  29  70  2014  MG  0.567164
270         Palmeiras  80  38  24   8  6  62  32  30  70  2016  SP  0.516129
310         Palmeiras  80  38  23  11  4  64  26  38  70  2018  SP  0.406250
70          São Paulo  78  38  22  12  4  66  32  34  68  2006  SP  0.484848
90          São Paulo  77  38  23   8  7  55  19  36  68  2007  SP  0.345455
190        Fluminense  77  38  22  11  5  61  33  28  67  2012  RJ  0.540984
210          Cruzeiro  76  38  23   7  8  77  37  40  67  2013  MG  0.480519
110         São Paulo  75  38  21  12  5  66  36  30  66  2008  SP  0.545455
290       Corinthians  72  38  21   9  8  50  30  20  63  2017  SP  0.600000
150        Fluminense  71  38  20  11  7  62  36  26  62  2010  RJ  0.580645
170       Corinthians  71  38  21   8  9  53  36  17  62  2011  SP  0.679245
350          Flamengo  71  38  21   8  9  68  48  20  62  2020  RJ  0.705882
130          Flamengo  67  38  19  10  9  58  44  14  59  2009  RJ  0.758621

#### 1.2 - Observações

Com a separação por número de jogos, notamos um padrão. Se observarmos os piores campeões, notamos que eles possuem metade do número de jogos como _vitórias_ (aproximadamente);

Aparenta ter um relação entre **GC** e **D** (Derrotas), quanto maior a **%_GC** maior o número de **derrotas**

- Ter metade ou mais de _vitórias_ com relação ao número de jogos é o requisito mínimo para ser campeão.
- Relação entre **%_GC** e **número de derrotas**

## 1.3 - Quantidade de campeões

In [101]:
df_campeoes.shape

(19, 15)

In [102]:
print(len(df_campeoes['Equipes'].unique()))
print(df_campeoes['Equipes'].unique())

8
['Cruzeiro' 'Santos' 'Corinthians' 'São Paulo' 'Flamengo' 'Fluminense'
 'Palmeiras' 'Atlético Mineiro']

In [103]:
df_campeoes.groupby(by='Equipes').count().sort_values(by='Pos.', ascending=False)

,Pos.,P,J,V,E,D,GP,GC,SG,%,Classificação ou rebaixamento,ano,fd,%_GC
Equipes,,,,,,,,,,,,,,
Corinthians,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Cruzeiro,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Flamengo,3,3,3,3,3,3,3,3,3,3,3,3,3,3
São Paulo,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Fluminense,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Palmeiras,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Atlético Mineiro,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Santos,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [105]:
df_campeoes.groupby(by='fd').count().sort_values(by='Pos.', ascending=False)

,Pos.,Equipes,P,J,V,E,D,GP,GC,SG,%,Classificação ou rebaixamento,ano,%_GC
fd,,,,,,,,,,,,,,
SP,10,10,10,10,10,10,10,10,10,10,10,10,10,10
RJ,5,5,5,5,5,5,5,5,5,5,5,5,5,5
MG,4,4,4,4,4,4,4,4,4,4,4,4,4,4

In [106]:
for numero_jogos in df_campeoes['J'].unique():
    print(f'Quantidade de jogos no campeonato: {numero_jogos}')
    df_group = df_campeoes[['Equipes', 'J']].groupby(by='J').get_group(numero_jogos)['Equipes'] 
    print(f'Quantidade de campeoes totais : {df_group.count().sum()}')
    print('Tabela de quantidade de títulos por Equipe')
    print(df_campeoes[columns].groupby(by='J').get_group(numero_jogos).groupby(by='Equipes').count())
    print('Tabela de quantidade de títulos por FD')
    print(df_campeoes[columns].groupby(by='J').get_group(numero_jogos).groupby(by='fd').count())
    print('\n')

Quantidade de jogos no campeonato: 46
Quantidade de campeoes totais : 2
Tabela de quantidade de títulos por Equipe
          P  J  V  E  D  GP  GC  SG  %  ano  fd  %_GC
Equipes
Cruzeiro  1  1  1  1  1   1   1   1  1    1   1     1
Santos    1  1  1  1  1   1   1   1  1    1   1     1
Tabela de quantidade de títulos por FD
    Equipes  P  J  V  E  D  GP  GC  SG  %  ano  %_GC
fd
MG        1  1  1  1  1  1   1   1   1  1    1     1
SP        1  1  1  1  1  1   1   1   1  1    1     1


Quantidade de jogos no campeonato: 42
Quantidade de campeoes totais : 1
Tabela de quantidade de títulos por Equipe
             P  J  V  E  D  GP  GC  SG  %  ano  fd  %_GC
Equipes
Corinthians  1  1  1  1  1   1   1   1  1    1   1     1
Tabela de quantidade de títulos por FD
    Equipes  P  J  V  E  D  GP  GC  SG  %  ano  %_GC
fd
SP        1  1  1  1  1  1   1   1   1  1    1     1


Quantidade de jogos no campeonato: 38
Quantidade de campeoes totais : 16
Tabela de quantidade de títulos por Equipe
                  P  J  V  E  D  GP  GC  SG  %  ano  fd  %_GC
Equipes
Atlético Mineiro  1  1  1  1  1   1   1   1  1    1   1     1
Corinthians       3  3  3  3  3   3   3   3  3    3   3     3
Cruzeiro          2  2  2  2  2   2   2   2  2    2   2     2
Flamengo          3  3  3  3  3   3   3   3  3    3   3     3
Fluminense        2  2  2  2  2   2   2   2  2    2   2     2
Palmeiras         2  2  2  2  2   2   2   2  2    2   2     2
São Paulo         3  3  3  3  3   3   3   3  3    3   3     3
Tabela de quantidade de títulos por FD
    Equipes  P  J  V  E  D  GP  GC  SG  %  ano  %_GC
fd
MG        3  3  3  3  3  3   3   3   3  3    3     3
RJ        5  5  5  5  5  5   5   5   5  5    5     5
SP        8  8  8  8  8  8   8   8   8  8    8     8

#### 1.3 - Observação

Fora realizados _19_ edições do Campeonato Brasileiro no formato de pontos corridos (2003 - 2021), delas, somente _8_ equipes sagraram-se campeãs.

No **ranking geral**, notamos que o **Corinthians** é o maior acumulador de títulos neste formato, com _4_.
Quando vamos a separação por número de jogos, notamos que o **Santos** é a única equipe que não aparece mais após a fixação em _38_ jogos.

Também notamos uma certa hegemonia regional entre **SP**, **RJ** e **MG**, sendo **SP** a região com maior número de equipes campeãs e maior quantidade de títulos.